export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAIL ='LOGIN_FAIL'
export const LOGIN_REQUEST='LOGIN_REQUEST'
export const LOGIN_OUT='LOGIN_OUT'
export const LOAD_PROFILE='LOAD_PROFILE'


export const HOME_VIDEO_SUCCESS='HOME_VIDEO_SUCCESS'
export const HOME_VIDEO_FAIL='HOME_VIDEO_FAIL'
export const HOME_VIDEO_REQUEST='HOME_VIDEO_REQUEST'

export const SELECTED_VIDEO_SUCCESS="SELECTED_VIDEO_SUCCESS"
export const SELECTED_VIDEO_REQUEST="SELECTED_VIDEO_REQUEST"
export const SELECTED_VIDEO_FAIL="SELECTED_VIDEO_FAIL"

export const CHANNEL_DETAILS_REQUEST="CHANNEL_DETAILS_REQUEST"
export const CHANNEL_DETAILS_SUCCESS="CHANNEL_DETAILS_SUCCESS"
export const CHANNEL_DETAILS_FAIL="CHANNEL_DETAILS_FAIL"

export const COMMENT_LIST_REQUEST="COMMENT_LIST_REQUEST"
export const COMMENT_LIST_SUCCESS="COMMENT_LIST_SUCCESS"
export const COMMENT_LIST_FAIL="COMMENT_LIST_FAIL"


export const SEARCH_VIDEOS_REQUEST="SEARCH_VIDEOS_REQUEST"
export const SEARCH_VIDEOS_SUCCESS="SEARCH_VIDEOS_SUCCESS"
export const SEARCH_VIDEOS_FAIL="SEARCH_VIDEOS_FAIL"


